package com.release.klinikgaharumedika.view.panel;

import com.release.klinikgaharumedika.controller.DashboardController;
import com.release.klinikgaharumedika.model.DashboardActiveQueuePage;
import com.release.klinikgaharumedika.model.DashboardData;
import com.release.klinikgaharumedika.model.DashboardQueueEntry;
import com.release.klinikgaharumedika.model.DashboardRecentVisit;
import com.release.klinikgaharumedika.model.DashboardRecentVisitPage;
import com.release.klinikgaharumedika.view.DashboardForm;
import java.awt.Color;
import java.awt.Component;
import java.awt.Window;
import java.beans.Beans;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class DashboardPanel extends javax.swing.JPanel {

    private static final Locale LOCALE_ID = Locale.forLanguageTag("id-ID");
    private static final Color COLOR_MUTED = new Color(120, 120, 120);
    private static final Color COLOR_SUCCESS = new Color(28, 112, 77);
    private static final Color COLOR_DANGER = new Color(208, 70, 55);
    private static final Color COLOR_WARNING = new Color(171, 116, 34);
    private static final Color COLOR_NEUTRAL = new Color(122, 122, 122);
    private static final int ACTIVE_QUEUE_PAGE_SIZE = 10;
    private static final int RECENT_VISITS_PAGE_SIZE = 10;
    private static final int DASHBOARD_TABLE_COLUMN_COUNT = 4;

    private final DashboardController dashboardController;
    private final JLabel activeQueueEmptyStateLabel = new JLabel("Data not found", SwingConstants.CENTER);
    private final JLabel recentVisitsEmptyStateLabel = new JLabel("Data not found", SwingConstants.CENTER);
    private int activeQueueCurrentPage = 1;
    private int activeQueueTotalPages = 1;
    private int activeQueueTotalItems = 0;
    private int recentVisitsCurrentPage = 1;
    private int recentVisitsTotalPages = 1;
    private int recentVisitsTotalItems = 0;
    private String recentVisitsSearchKeyword = "";

    public DashboardPanel() {
        initComponents();
        configureActiveQueueTable();
        configureRecentVisitsTable();
        setupSearch();
        FormUiStyle.applyFormStyle(this);
        if (Beans.isDesignTime()) {
            dashboardController = null;
            return;
        }

        dashboardController = new DashboardController();
        initializeRuntimeState();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelTopBar = new javax.swing.JPanel();
        lblPageTitle = new javax.swing.JLabel();
        lblPageDate = new javax.swing.JLabel();
        btnRegisterPatient = new javax.swing.JButton();
        panelStatsRow = new javax.swing.JPanel();
        panelStatTodayVisits = new javax.swing.JPanel();
        lblStatTodayVisitsTitle = new javax.swing.JLabel();
        lblStatTodayVisitsValue = new javax.swing.JLabel();
        lblStatTodayVisitsInfo = new javax.swing.JLabel();
        panelStatPatients = new javax.swing.JPanel();
        lblStatPatientsTitle = new javax.swing.JLabel();
        lblStatPatientsValue = new javax.swing.JLabel();
        lblStatPatientsInfo = new javax.swing.JLabel();
        panelStatRevenue = new javax.swing.JPanel();
        lblStatRevenueTitle = new javax.swing.JLabel();
        lblStatRevenueValue = new javax.swing.JLabel();
        lblStatRevenueInfo = new javax.swing.JLabel();
        panelStatLowStock = new javax.swing.JPanel();
        lblStatLowStockTitle = new javax.swing.JLabel();
        lblStatLowStockValue = new javax.swing.JLabel();
        lblStatLowStockInfo = new javax.swing.JLabel();
        panelContentRow = new javax.swing.JPanel();
        panelLatestVisits = new javax.swing.JPanel();
        lblLatestVisitsTitle = new javax.swing.JLabel();
        lblSeeAll = new javax.swing.JLabel();
        txtSearchRecentVisits = new javax.swing.JTextField();
        btnSearchRecentVisits = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblRecentVisitsPageInfo = new javax.swing.JLabel();
        btnPrevRecentVisits = new javax.swing.JButton();
        btnNextRecentVisits = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataKunjungan = new javax.swing.JTable();
        panelRightStack = new javax.swing.JPanel();
        panelActiveQueue = new javax.swing.JPanel();
        lblActiveQueueTitle = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblActiveQueuePageInfo = new javax.swing.JLabel();
        btnPrevActiveQueues = new javax.swing.JButton();
        btnNextActiveQueues = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDataAntrianAktif = new javax.swing.JTable();
        panelQuickAccess = new javax.swing.JPanel();
        lblQuickAccessTitle = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnQuickAddPatient = new javax.swing.JButton();
        btnQuickExamination = new javax.swing.JButton();
        btnQuickPayment = new javax.swing.JButton();
        btnQuickReport = new javax.swing.JButton();

        panelMain.setBackground(new java.awt.Color(243, 240, 233));

        panelTopBar.setBackground(new java.awt.Color(255, 255, 255));
        panelTopBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 218, 208)));

        lblPageTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPageTitle.setForeground(new java.awt.Color(32, 32, 32));
        lblPageTitle.setText("Dashboard");

        lblPageDate.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblPageDate.setForeground(new java.awt.Color(120, 120, 120));
        lblPageDate.setText("Senin, 07 April 2025");

        btnRegisterPatient.setBackground(new java.awt.Color(28, 112, 77));
        btnRegisterPatient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegisterPatient.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterPatient.setText("+ Daftarkan Pasien");
        btnRegisterPatient.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 14, 1, 14));
        btnRegisterPatient.setFocusPainted(false);
        btnRegisterPatient.setOpaque(true);
        btnRegisterPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterPatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTopBarLayout = new javax.swing.GroupLayout(panelTopBar);
        panelTopBar.setLayout(panelTopBarLayout);
        panelTopBarLayout.setHorizontalGroup(
            panelTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopBarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPageTitle)
                    .addComponent(lblPageDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegisterPatient)
                .addGap(14, 14, 14))
        );
        panelTopBarLayout.setVerticalGroup(
            panelTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopBarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTopBarLayout.createSequentialGroup()
                        .addComponent(lblPageTitle)
                        .addGap(0, 0, 0)
                        .addComponent(lblPageDate))
                    .addComponent(btnRegisterPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        panelStatsRow.setBackground(new java.awt.Color(243, 240, 233));

        panelStatTodayVisits.setBackground(new java.awt.Color(243, 240, 233));

        lblStatTodayVisitsTitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblStatTodayVisitsTitle.setForeground(new java.awt.Color(120, 120, 120));
        lblStatTodayVisitsTitle.setText("Kunjungan hari ini");

        lblStatTodayVisitsValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStatTodayVisitsValue.setForeground(new java.awt.Color(32, 32, 32));
        lblStatTodayVisitsValue.setText("24");
        lblStatTodayVisitsValue.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblStatTodayVisitsValueAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblStatTodayVisitsInfo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblStatTodayVisitsInfo.setForeground(new java.awt.Color(28, 112, 77));
        lblStatTodayVisitsInfo.setText("+6 dari kemarin");

        javax.swing.GroupLayout panelStatTodayVisitsLayout = new javax.swing.GroupLayout(panelStatTodayVisits);
        panelStatTodayVisits.setLayout(panelStatTodayVisitsLayout);
        panelStatTodayVisitsLayout.setHorizontalGroup(
            panelStatTodayVisitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatTodayVisitsLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelStatTodayVisitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatTodayVisitsTitle)
                    .addComponent(lblStatTodayVisitsValue)
                    .addComponent(lblStatTodayVisitsInfo)))
        );
        panelStatTodayVisitsLayout.setVerticalGroup(
            panelStatTodayVisitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatTodayVisitsLayout.createSequentialGroup()
                .addComponent(lblStatTodayVisitsTitle)
                .addGap(3, 3, 3)
                .addComponent(lblStatTodayVisitsValue)
                .addGap(3, 3, 3)
                .addComponent(lblStatTodayVisitsInfo))
        );

        panelStatPatients.setBackground(new java.awt.Color(243, 240, 233));

        lblStatPatientsTitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblStatPatientsTitle.setForeground(new java.awt.Color(120, 120, 120));
        lblStatPatientsTitle.setText("Total pasien");

        lblStatPatientsValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStatPatientsValue.setForeground(new java.awt.Color(32, 32, 32));
        lblStatPatientsValue.setText("1.482");

        lblStatPatientsInfo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblStatPatientsInfo.setForeground(new java.awt.Color(28, 112, 77));
        lblStatPatientsInfo.setText("+12 bulan ini");

        javax.swing.GroupLayout panelStatPatientsLayout = new javax.swing.GroupLayout(panelStatPatients);
        panelStatPatients.setLayout(panelStatPatientsLayout);
        panelStatPatientsLayout.setHorizontalGroup(
            panelStatPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatPatientsLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelStatPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatPatientsTitle)
                    .addComponent(lblStatPatientsValue)
                    .addComponent(lblStatPatientsInfo)))
        );
        panelStatPatientsLayout.setVerticalGroup(
            panelStatPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatPatientsLayout.createSequentialGroup()
                .addComponent(lblStatPatientsTitle)
                .addGap(3, 3, 3)
                .addComponent(lblStatPatientsValue)
                .addGap(3, 3, 3)
                .addComponent(lblStatPatientsInfo))
        );

        panelStatRevenue.setBackground(new java.awt.Color(243, 240, 233));

        lblStatRevenueTitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblStatRevenueTitle.setForeground(new java.awt.Color(120, 120, 120));
        lblStatRevenueTitle.setText("Pendapatan hari ini");

        lblStatRevenueValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStatRevenueValue.setForeground(new java.awt.Color(32, 32, 32));
        lblStatRevenueValue.setText("Rp 3,2jt");

        lblStatRevenueInfo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblStatRevenueInfo.setForeground(new java.awt.Color(28, 112, 77));
        lblStatRevenueInfo.setText("+18% rata-rata");

        javax.swing.GroupLayout panelStatRevenueLayout = new javax.swing.GroupLayout(panelStatRevenue);
        panelStatRevenue.setLayout(panelStatRevenueLayout);
        panelStatRevenueLayout.setHorizontalGroup(
            panelStatRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatRevenueLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelStatRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatRevenueTitle)
                    .addComponent(lblStatRevenueValue)
                    .addComponent(lblStatRevenueInfo)))
        );
        panelStatRevenueLayout.setVerticalGroup(
            panelStatRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatRevenueLayout.createSequentialGroup()
                .addComponent(lblStatRevenueTitle)
                .addGap(3, 3, 3)
                .addComponent(lblStatRevenueValue)
                .addGap(3, 3, 3)
                .addComponent(lblStatRevenueInfo))
        );

        panelStatLowStock.setBackground(new java.awt.Color(243, 240, 233));

        lblStatLowStockTitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblStatLowStockTitle.setForeground(new java.awt.Color(120, 120, 120));
        lblStatLowStockTitle.setText("Stok obat menipis");

        lblStatLowStockValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStatLowStockValue.setForeground(new java.awt.Color(32, 32, 32));
        lblStatLowStockValue.setText("3");

        lblStatLowStockInfo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblStatLowStockInfo.setForeground(new java.awt.Color(208, 70, 55));
        lblStatLowStockInfo.setText("Perlu restock");

        javax.swing.GroupLayout panelStatLowStockLayout = new javax.swing.GroupLayout(panelStatLowStock);
        panelStatLowStock.setLayout(panelStatLowStockLayout);
        panelStatLowStockLayout.setHorizontalGroup(
            panelStatLowStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatLowStockLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelStatLowStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatLowStockTitle)
                    .addComponent(lblStatLowStockValue)
                    .addComponent(lblStatLowStockInfo)))
        );
        panelStatLowStockLayout.setVerticalGroup(
            panelStatLowStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatLowStockLayout.createSequentialGroup()
                .addComponent(lblStatLowStockTitle)
                .addGap(3, 3, 3)
                .addComponent(lblStatLowStockValue)
                .addGap(3, 3, 3)
                .addComponent(lblStatLowStockInfo))
        );

        javax.swing.GroupLayout panelStatsRowLayout = new javax.swing.GroupLayout(panelStatsRow);
        panelStatsRow.setLayout(panelStatsRowLayout);
        panelStatsRowLayout.setHorizontalGroup(
            panelStatsRowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatsRowLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(panelStatTodayVisits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(panelStatPatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(panelStatRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(panelStatLowStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
        panelStatsRowLayout.setVerticalGroup(
            panelStatsRowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelStatTodayVisits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelStatPatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelStatRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelStatLowStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelContentRow.setBackground(new java.awt.Color(243, 240, 233));

        panelLatestVisits.setBackground(new java.awt.Color(255, 255, 255));
        panelLatestVisits.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 218, 208)));

        lblLatestVisitsTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblLatestVisitsTitle.setForeground(new java.awt.Color(36, 36, 36));
        lblLatestVisitsTitle.setText("Kunjungan terbaru");

        lblSeeAll.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblSeeAll.setForeground(new java.awt.Color(28, 112, 77));
        lblSeeAll.setText("Cari");

        txtSearchRecentVisits.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtSearchRecentVisits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchRecentVisitsActionPerformed(evt);
            }
        });

        btnSearchRecentVisits.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSearchRecentVisits.setForeground(new java.awt.Color(96, 96, 96));
        btnSearchRecentVisits.setText("Cari");
        btnSearchRecentVisits.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 213, 203)));
        btnSearchRecentVisits.setFocusPainted(false);
        btnSearchRecentVisits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchRecentVisitsActionPerformed(evt);
            }
        });

        lblRecentVisitsPageInfo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblRecentVisitsPageInfo.setForeground(new java.awt.Color(120, 120, 120));
        lblRecentVisitsPageInfo.setText("Halaman 1 dari 1");

        btnPrevRecentVisits.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnPrevRecentVisits.setForeground(new java.awt.Color(96, 96, 96));
        btnPrevRecentVisits.setText("Sebelumnya");
        btnPrevRecentVisits.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 213, 203)));
        btnPrevRecentVisits.setFocusPainted(false);
        btnPrevRecentVisits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevRecentVisitsActionPerformed(evt);
            }
        });

        btnNextRecentVisits.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnNextRecentVisits.setForeground(new java.awt.Color(96, 96, 96));
        btnNextRecentVisits.setText("Berikutnya");
        btnNextRecentVisits.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 213, 203)));
        btnNextRecentVisits.setFocusPainted(false);
        btnNextRecentVisits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextRecentVisitsActionPerformed(evt);
            }
        });

        tblDataKunjungan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ANTRIAN", "PASIEN", "DOKTER", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDataKunjungan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblDataKunjungan.setRowHeight(25);
        tblDataKunjungan.setShowHorizontalLines(true);
        tblDataKunjungan.setShowVerticalLines(true);
        tblDataKunjungan.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDataKunjungan);

        javax.swing.GroupLayout panelLatestVisitsLayout = new javax.swing.GroupLayout(panelLatestVisits);
        panelLatestVisits.setLayout(panelLatestVisitsLayout);
        panelLatestVisitsLayout.setHorizontalGroup(
            panelLatestVisitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLatestVisitsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelLatestVisitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLatestVisitsLayout.createSequentialGroup()
                        .addComponent(lblLatestVisitsTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(lblSeeAll)
                        .addGap(6, 6, 6)
                        .addComponent(txtSearchRecentVisits, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnSearchRecentVisits, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLatestVisitsLayout.createSequentialGroup()
                        .addComponent(lblRecentVisitsPageInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrevRecentVisits, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnNextRecentVisits, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        panelLatestVisitsLayout.setVerticalGroup(
            panelLatestVisitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLatestVisitsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelLatestVisitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLatestVisitsTitle)
                    .addComponent(lblSeeAll)
                    .addComponent(txtSearchRecentVisits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchRecentVisits))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLatestVisitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRecentVisitsPageInfo)
                    .addComponent(btnPrevRecentVisits)
                    .addComponent(btnNextRecentVisits))
                .addGap(14, 14, 14))
        );

        panelRightStack.setBackground(new java.awt.Color(243, 240, 233));

        panelActiveQueue.setBackground(new java.awt.Color(255, 255, 255));
        panelActiveQueue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 218, 208)));

        lblActiveQueueTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblActiveQueueTitle.setText("Antrian aktif");

        lblActiveQueuePageInfo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblActiveQueuePageInfo.setForeground(new java.awt.Color(120, 120, 120));
        lblActiveQueuePageInfo.setText("Halaman 1 dari 1");

        btnPrevActiveQueues.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnPrevActiveQueues.setForeground(new java.awt.Color(96, 96, 96));
        btnPrevActiveQueues.setText("Sebelumnya");
        btnPrevActiveQueues.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 213, 203)));
        btnPrevActiveQueues.setFocusPainted(false);
        btnPrevActiveQueues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActiveQueuesActionPerformed(evt);
            }
        });

        btnNextActiveQueues.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnNextActiveQueues.setForeground(new java.awt.Color(96, 96, 96));
        btnNextActiveQueues.setText("Berikutnya");
        btnNextActiveQueues.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 213, 203)));
        btnNextActiveQueues.setFocusPainted(false);
        btnNextActiveQueues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActiveQueuesActionPerformed(evt);
            }
        });

        tblDataAntrianAktif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ANTRIAN", "PASIEN", "DOKTER / POLI", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDataAntrianAktif.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblDataAntrianAktif.setRowHeight(25);
        tblDataAntrianAktif.setShowHorizontalLines(true);
        tblDataAntrianAktif.setShowVerticalLines(true);
        tblDataAntrianAktif.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblDataAntrianAktif);

        javax.swing.GroupLayout panelActiveQueueLayout = new javax.swing.GroupLayout(panelActiveQueue);
        panelActiveQueue.setLayout(panelActiveQueueLayout);
        panelActiveQueueLayout.setHorizontalGroup(
            panelActiveQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActiveQueueLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelActiveQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelActiveQueueLayout.createSequentialGroup()
                        .addComponent(lblActiveQueueTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelActiveQueueLayout.createSequentialGroup()
                        .addComponent(lblActiveQueuePageInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrevActiveQueues, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnNextActiveQueues, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        panelActiveQueueLayout.setVerticalGroup(
            panelActiveQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActiveQueueLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblActiveQueueTitle)
                .addGap(10, 10, 10)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelActiveQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActiveQueuePageInfo)
                    .addComponent(btnPrevActiveQueues)
                    .addComponent(btnNextActiveQueues))
                .addGap(14, 14, 14))
        );

        panelQuickAccess.setBackground(new java.awt.Color(255, 255, 255));
        panelQuickAccess.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 218, 208)));

        lblQuickAccessTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblQuickAccessTitle.setText("Akses cepat");

        btnQuickAddPatient.setBackground(new java.awt.Color(28, 112, 77));
        btnQuickAddPatient.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnQuickAddPatient.setForeground(new java.awt.Color(255, 255, 255));
        btnQuickAddPatient.setText("Tambah Pasien Baru");
        btnQuickAddPatient.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 12, 1, 12));
        btnQuickAddPatient.setFocusPainted(false);
        btnQuickAddPatient.setOpaque(true);
        btnQuickAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickAddPatientActionPerformed(evt);
            }
        });

        btnQuickExamination.setBackground(new java.awt.Color(28, 112, 77));
        btnQuickExamination.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnQuickExamination.setForeground(new java.awt.Color(255, 255, 255));
        btnQuickExamination.setText("Input Pemeriksaan");
        btnQuickExamination.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 218, 208)));
        btnQuickExamination.setFocusPainted(false);
        btnQuickExamination.setOpaque(true);
        btnQuickExamination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickExaminationActionPerformed(evt);
            }
        });

        btnQuickPayment.setBackground(new java.awt.Color(28, 112, 77));
        btnQuickPayment.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnQuickPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnQuickPayment.setText("Proses Pembayaran");
        btnQuickPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 218, 208)));
        btnQuickPayment.setFocusPainted(false);
        btnQuickPayment.setOpaque(true);
        btnQuickPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickPaymentActionPerformed(evt);
            }
        });

        btnQuickReport.setBackground(new java.awt.Color(28, 112, 77));
        btnQuickReport.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnQuickReport.setForeground(new java.awt.Color(255, 255, 255));
        btnQuickReport.setText("Cetak Laporan Hari Ini");
        btnQuickReport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 218, 208)));
        btnQuickReport.setFocusPainted(false);
        btnQuickReport.setOpaque(true);
        btnQuickReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelQuickAccessLayout = new javax.swing.GroupLayout(panelQuickAccess);
        panelQuickAccess.setLayout(panelQuickAccessLayout);
        panelQuickAccessLayout.setHorizontalGroup(
            panelQuickAccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuickAccessLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelQuickAccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuickAccessTitle)
                    .addComponent(jSeparator3)
                    .addComponent(btnQuickAddPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuickExamination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuickPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuickReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        panelQuickAccessLayout.setVerticalGroup(
            panelQuickAccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuickAccessLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblQuickAccessTitle)
                .addGap(10, 10, 10)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnQuickAddPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuickExamination, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuickPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuickReport, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRightStackLayout = new javax.swing.GroupLayout(panelRightStack);
        panelRightStack.setLayout(panelRightStackLayout);
        panelRightStackLayout.setHorizontalGroup(
            panelRightStackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelActiveQueue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelQuickAccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRightStackLayout.setVerticalGroup(
            panelRightStackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRightStackLayout.createSequentialGroup()
                .addComponent(panelActiveQueue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panelQuickAccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelContentRowLayout = new javax.swing.GroupLayout(panelContentRow);
        panelContentRow.setLayout(panelContentRowLayout);
        panelContentRowLayout.setHorizontalGroup(
            panelContentRowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentRowLayout.createSequentialGroup()
                .addComponent(panelLatestVisits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(panelRightStack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelContentRowLayout.setVerticalGroup(
            panelContentRowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLatestVisits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelRightStack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelStatsRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelContentRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panelStatsRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panelContentRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchRecentVisitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchRecentVisitsActionPerformed
        performRecentVisitSearch();
    }//GEN-LAST:event_txtSearchRecentVisitsActionPerformed

    private void btnSearchRecentVisitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchRecentVisitsActionPerformed
        performRecentVisitSearch();
    }//GEN-LAST:event_btnSearchRecentVisitsActionPerformed

    private void btnPrevRecentVisitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevRecentVisitsActionPerformed
        if (recentVisitsCurrentPage > 1) {
            loadRecentVisitPage(recentVisitsCurrentPage - 1);
        }
    }//GEN-LAST:event_btnPrevRecentVisitsActionPerformed

    private void btnNextRecentVisitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextRecentVisitsActionPerformed
        if (recentVisitsCurrentPage < recentVisitsTotalPages) {
            loadRecentVisitPage(recentVisitsCurrentPage + 1);
        }
    }//GEN-LAST:event_btnNextRecentVisitsActionPerformed

    private void btnRegisterPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterPatientActionPerformed
        navigateToPasienCreatePage();
    }//GEN-LAST:event_btnRegisterPatientActionPerformed

    private void btnPrevActiveQueuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActiveQueuesActionPerformed
        if (activeQueueCurrentPage > 1) {
            loadActiveQueuePage(activeQueueCurrentPage - 1);
        }
    }//GEN-LAST:event_btnPrevActiveQueuesActionPerformed

    private void btnNextActiveQueuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActiveQueuesActionPerformed
        if (activeQueueCurrentPage < activeQueueTotalPages) {
            loadActiveQueuePage(activeQueueCurrentPage + 1);
        }
    }//GEN-LAST:event_btnNextActiveQueuesActionPerformed

    private void btnQuickAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickAddPatientActionPerformed
        navigateToPasienCreatePage();
    }//GEN-LAST:event_btnQuickAddPatientActionPerformed

    private void btnQuickExaminationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickExaminationActionPerformed
        navigateToKunjunganExaminationPage();
    }//GEN-LAST:event_btnQuickExaminationActionPerformed

    private void btnQuickPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickPaymentActionPerformed
        navigateToPembayaranListPage();
    }//GEN-LAST:event_btnQuickPaymentActionPerformed

    private void btnQuickReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickReportActionPerformed
        navigateToDailyReportPage();
    }//GEN-LAST:event_btnQuickReportActionPerformed

    private void lblStatTodayVisitsValueAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblStatTodayVisitsValueAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblStatTodayVisitsValueAncestorAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNextActiveQueues;
    private javax.swing.JButton btnNextRecentVisits;
    private javax.swing.JButton btnPrevActiveQueues;
    private javax.swing.JButton btnPrevRecentVisits;
    private javax.swing.JButton btnQuickAddPatient;
    private javax.swing.JButton btnQuickExamination;
    private javax.swing.JButton btnQuickPayment;
    private javax.swing.JButton btnQuickReport;
    private javax.swing.JButton btnRegisterPatient;
    private javax.swing.JButton btnSearchRecentVisits;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblActiveQueuePageInfo;
    private javax.swing.JLabel lblActiveQueueTitle;
    private javax.swing.JLabel lblLatestVisitsTitle;
    private javax.swing.JLabel lblPageDate;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblQuickAccessTitle;
    private javax.swing.JLabel lblRecentVisitsPageInfo;
    private javax.swing.JLabel lblSeeAll;
    private javax.swing.JLabel lblStatLowStockInfo;
    private javax.swing.JLabel lblStatLowStockTitle;
    private javax.swing.JLabel lblStatLowStockValue;
    private javax.swing.JLabel lblStatPatientsInfo;
    private javax.swing.JLabel lblStatPatientsTitle;
    private javax.swing.JLabel lblStatPatientsValue;
    private javax.swing.JLabel lblStatRevenueInfo;
    private javax.swing.JLabel lblStatRevenueTitle;
    private javax.swing.JLabel lblStatRevenueValue;
    private javax.swing.JLabel lblStatTodayVisitsInfo;
    private javax.swing.JLabel lblStatTodayVisitsTitle;
    private javax.swing.JLabel lblStatTodayVisitsValue;
    private javax.swing.JPanel panelActiveQueue;
    private javax.swing.JPanel panelContentRow;
    private javax.swing.JPanel panelLatestVisits;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelQuickAccess;
    private javax.swing.JPanel panelRightStack;
    private javax.swing.JPanel panelStatLowStock;
    private javax.swing.JPanel panelStatPatients;
    private javax.swing.JPanel panelStatRevenue;
    private javax.swing.JPanel panelStatTodayVisits;
    private javax.swing.JPanel panelStatsRow;
    private javax.swing.JPanel panelTopBar;
    private javax.swing.JTable tblDataAntrianAktif;
    private javax.swing.JTable tblDataKunjungan;
    private javax.swing.JTextField txtSearchRecentVisits;
    // End of variables declaration//GEN-END:variables

    private void initializeRuntimeState() {
        applyCurrentDate();
        setLoadingState();
        loadDashboardStats();
        loadActiveQueuePage(1);
        loadRecentVisitPage(1);
    }

    private void configureActiveQueueTable() {
        tblDataAntrianAktif.setDefaultEditor(Object.class, null);
        tblDataAntrianAktif.setBackground(Color.WHITE);
        tblDataAntrianAktif.setForeground(new Color(32, 32, 32));
        tblDataAntrianAktif.setFont(new java.awt.Font("Segoe UI", 0, 12));
        tblDataAntrianAktif.setRowHeight(34);
        tblDataAntrianAktif.setFocusable(false);
        tblDataAntrianAktif.setRowSelectionAllowed(false);
        tblDataAntrianAktif.setCellSelectionEnabled(false);
        tblDataAntrianAktif.setShowVerticalLines(false);
        tblDataAntrianAktif.setShowHorizontalLines(true);
        tblDataAntrianAktif.setGridColor(new Color(232, 229, 221));
        tblDataAntrianAktif.setIntercellSpacing(new java.awt.Dimension(0, 1));
        tblDataAntrianAktif.setFillsViewportHeight(true);
        tblDataAntrianAktif.getTableHeader().setReorderingAllowed(false);
        tblDataAntrianAktif.getTableHeader().setResizingAllowed(false);
        tblDataAntrianAktif.getTableHeader().setBackground(new Color(244, 241, 234));
        tblDataAntrianAktif.getTableHeader().setForeground(new Color(118, 118, 118));
        tblDataAntrianAktif.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 10));

        if (tblDataAntrianAktif.getColumnModel().getColumnCount() == DASHBOARD_TABLE_COLUMN_COUNT) {
            tblDataAntrianAktif.getColumnModel().getColumn(0).setMinWidth(82);
            tblDataAntrianAktif.getColumnModel().getColumn(0).setMaxWidth(82);
            tblDataAntrianAktif.getColumnModel().getColumn(0).setCellRenderer(new PaddedTableCellRenderer(SwingConstants.CENTER));
            tblDataAntrianAktif.getColumnModel().getColumn(1).setPreferredWidth(140);
            tblDataAntrianAktif.getColumnModel().getColumn(1).setCellRenderer(new PaddedTableCellRenderer(SwingConstants.LEFT));
            tblDataAntrianAktif.getColumnModel().getColumn(2).setPreferredWidth(180);
            tblDataAntrianAktif.getColumnModel().getColumn(2).setCellRenderer(new PaddedTableCellRenderer(SwingConstants.LEFT));
            tblDataAntrianAktif.getColumnModel().getColumn(3).setMinWidth(96);
            tblDataAntrianAktif.getColumnModel().getColumn(3).setMaxWidth(96);
            tblDataAntrianAktif.getColumnModel().getColumn(3).setCellRenderer(new StatusTableCellRenderer());
        }

        jScrollPane2.setBorder(BorderFactory.createEmptyBorder());
        jScrollPane2.getViewport().setBackground(Color.WHITE);
        jScrollPane2.setBackground(Color.WHITE);
        jScrollPane2.setColumnHeaderView(tblDataAntrianAktif.getTableHeader());

        activeQueueEmptyStateLabel.setOpaque(true);
        activeQueueEmptyStateLabel.setBackground(Color.WHITE);
        activeQueueEmptyStateLabel.setForeground(COLOR_MUTED);
        activeQueueEmptyStateLabel.setFont(new java.awt.Font("Segoe UI", 0, 12));
        activeQueueEmptyStateLabel.setBorder(BorderFactory.createEmptyBorder(12, 12, 12, 12));

        updateActiveQueuePaginationInfo();
        showActiveQueuesTable();
    }

    private void configureRecentVisitsTable() {
        tblDataKunjungan.setDefaultEditor(Object.class, null);
        tblDataKunjungan.setBackground(Color.WHITE);
        tblDataKunjungan.setForeground(new Color(32, 32, 32));
        tblDataKunjungan.setFont(new java.awt.Font("Segoe UI", 0, 12));
        tblDataKunjungan.setRowHeight(34);
        tblDataKunjungan.setFocusable(false);
        tblDataKunjungan.setRowSelectionAllowed(false);
        tblDataKunjungan.setCellSelectionEnabled(false);
        tblDataKunjungan.setShowVerticalLines(false);
        tblDataKunjungan.setShowHorizontalLines(true);
        tblDataKunjungan.setGridColor(new Color(232, 229, 221));
        tblDataKunjungan.setIntercellSpacing(new java.awt.Dimension(0, 1));
        tblDataKunjungan.setFillsViewportHeight(true);
        tblDataKunjungan.getTableHeader().setReorderingAllowed(false);
        tblDataKunjungan.getTableHeader().setResizingAllowed(false);
        tblDataKunjungan.getTableHeader().setBackground(new Color(244, 241, 234));
        tblDataKunjungan.getTableHeader().setForeground(new Color(118, 118, 118));
        tblDataKunjungan.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 10));

        if (tblDataKunjungan.getColumnModel().getColumnCount() == DASHBOARD_TABLE_COLUMN_COUNT) {
            tblDataKunjungan.getColumnModel().getColumn(0).setMinWidth(90);
            tblDataKunjungan.getColumnModel().getColumn(0).setMaxWidth(90);
            tblDataKunjungan.getColumnModel().getColumn(0).setCellRenderer(new PaddedTableCellRenderer(SwingConstants.CENTER));
            tblDataKunjungan.getColumnModel().getColumn(1).setPreferredWidth(180);
            tblDataKunjungan.getColumnModel().getColumn(1).setCellRenderer(new PaddedTableCellRenderer(SwingConstants.LEFT));
            tblDataKunjungan.getColumnModel().getColumn(2).setPreferredWidth(220);
            tblDataKunjungan.getColumnModel().getColumn(2).setCellRenderer(new PaddedTableCellRenderer(SwingConstants.LEFT));
            tblDataKunjungan.getColumnModel().getColumn(3).setMinWidth(120);
            tblDataKunjungan.getColumnModel().getColumn(3).setMaxWidth(120);
            tblDataKunjungan.getColumnModel().getColumn(3).setCellRenderer(new StatusTableCellRenderer());
        }

        jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        jScrollPane1.setBackground(Color.WHITE);
        jScrollPane1.setColumnHeaderView(tblDataKunjungan.getTableHeader());

        recentVisitsEmptyStateLabel.setOpaque(true);
        recentVisitsEmptyStateLabel.setBackground(Color.WHITE);
        recentVisitsEmptyStateLabel.setForeground(COLOR_MUTED);
        recentVisitsEmptyStateLabel.setFont(new java.awt.Font("Segoe UI", 0, 12));
        recentVisitsEmptyStateLabel.setBorder(BorderFactory.createEmptyBorder(12, 12, 12, 12));

        updateRecentVisitPaginationInfo();
        showRecentVisitsTable();
    }

    private void setupSearch() {
        txtSearchRecentVisits.putClientProperty(
                "JTextField.placeholderText",
                "Contoh: A001 / Ahmad Fauzi / dr. Andi Saputra"
        );
    }

    // Flow utama statistik: View -> Controller -> Repository -> Model -> View.
    public final void loadDashboardStats() {
        SwingWorker<DashboardData, Void> worker = new SwingWorker<>() {
            @Override
            protected DashboardData doInBackground() throws Exception {
                return dashboardController.loadDashboardStats();
            }

            @Override
            protected void done() {
                try {
                    applyDashboardStats(get());
                } catch (Exception exception) {
                    applyLoadError(exception);
                }
            }
        };

        worker.execute();
    }

    private void loadActiveQueuePage(int page) {
        final int targetPage = Math.max(page, 1);
        setActiveQueueLoadingState();

        SwingWorker<DashboardActiveQueuePage, Void> worker = new SwingWorker<>() {
            @Override
            protected DashboardActiveQueuePage doInBackground() throws Exception {
                return dashboardController.loadActiveQueuePage(targetPage, ACTIVE_QUEUE_PAGE_SIZE);
            }

            @Override
            protected void done() {
                try {
                    applyActiveQueuePage(get());
                } catch (Exception exception) {
                    activeQueueCurrentPage = 1;
                    activeQueueTotalPages = 1;
                    activeQueueTotalItems = 0;
                    applyActiveQueuePlaceholder("Gagal memuat antrian");
                    updateActiveQueuePaginationInfo();
                    btnPrevActiveQueues.setEnabled(false);
                    btnNextActiveQueues.setEnabled(false);
                }
            }
        };

        worker.execute();
    }

    private void loadRecentVisitPage(int page) {
        final int targetPage = Math.max(page, 1);
        final String keyword = recentVisitsSearchKeyword;
        setRecentVisitLoadingState();

        SwingWorker<DashboardRecentVisitPage, Void> worker = new SwingWorker<>() {
            @Override
            protected DashboardRecentVisitPage doInBackground() throws Exception {
                return dashboardController.loadRecentVisitPage(targetPage, RECENT_VISITS_PAGE_SIZE, keyword);
            }

            @Override
            protected void done() {
                try {
                    applyRecentVisitPage(get());
                } catch (Exception exception) {
                    recentVisitsCurrentPage = 1;
                    recentVisitsTotalPages = 1;
                    recentVisitsTotalItems = 0;
                    applyRecentVisitPlaceholder("Gagal memuat data kunjungan");
                    updateRecentVisitPaginationInfo();
                    btnPrevRecentVisits.setEnabled(false);
                    btnNextRecentVisits.setEnabled(false);
                    btnSearchRecentVisits.setEnabled(true);
                    txtSearchRecentVisits.setEnabled(true);
                }
            }
        };

        worker.execute();
    }

    private void applyCurrentDate() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE, dd MMMM yyyy", LOCALE_ID);
        String formattedDate = LocalDate.now().format(formatter);
        lblPageDate.setText(capitalizeFirstLetter(formattedDate));
    }

    private void setLoadingState() {
        lblStatTodayVisitsValue.setText("...");
        lblStatTodayVisitsInfo.setText("Memuat data");
        lblStatTodayVisitsInfo.setForeground(COLOR_MUTED);

        lblStatPatientsValue.setText("...");
        lblStatPatientsInfo.setText("Memuat data");
        lblStatPatientsInfo.setForeground(COLOR_MUTED);

        lblStatRevenueValue.setText("...");
        lblStatRevenueInfo.setText("Memuat data");
        lblStatRevenueInfo.setForeground(COLOR_MUTED);

        lblStatLowStockValue.setText("...");
        lblStatLowStockInfo.setText("Memuat data");
        lblStatLowStockInfo.setForeground(COLOR_MUTED);

        setActiveQueueLoadingState();
        setRecentVisitLoadingState();
    }

    private void setActiveQueueLoadingState() {
        btnPrevActiveQueues.setEnabled(false);
        btnNextActiveQueues.setEnabled(false);
        applyActiveQueuePlaceholder("Memuat antrian...");
    }

    private void setRecentVisitLoadingState() {
        btnSearchRecentVisits.setEnabled(false);
        txtSearchRecentVisits.setEnabled(false);
        btnPrevRecentVisits.setEnabled(false);
        btnNextRecentVisits.setEnabled(false);
        applyRecentVisitPlaceholder("Memuat data kunjungan...");
    }

    private void performRecentVisitSearch() {
        recentVisitsSearchKeyword = txtSearchRecentVisits.getText() == null
                ? ""
                : txtSearchRecentVisits.getText().trim();
        loadRecentVisitPage(1);
    }

    private void applyDashboardStats(DashboardData data) {
        panelMain.setToolTipText(null);
        applyTodayVisitsStat(data);
        applyTotalPatientsStat(data);
        applyTodayRevenueStat(data);
        applyLowStockStat(data);
    }

    private void applyTodayVisitsStat(DashboardData data) {
        int visitsDelta = data.getVisitsToday() - data.getVisitsYesterday();
        lblStatTodayVisitsValue.setText(formatInteger(data.getVisitsToday()));
        lblStatTodayVisitsInfo.setText(buildVisitInfoText(visitsDelta));
        lblStatTodayVisitsInfo.setForeground(resolveDeltaColor(visitsDelta));
    }

    private void applyTotalPatientsStat(DashboardData data) {
        lblStatPatientsValue.setText(formatInteger(data.getTotalPatients()));
        lblStatPatientsInfo.setText(buildMonthlyPatientInfoText(data.getNewPatientsThisMonth()));
        lblStatPatientsInfo.setForeground(data.getNewPatientsThisMonth() > 0 ? COLOR_SUCCESS : COLOR_MUTED);
    }

    private void applyTodayRevenueStat(DashboardData data) {
        lblStatRevenueValue.setText(formatCompactCurrency(data.getTodayRevenue()));
        lblStatRevenueInfo.setText(buildRevenueInfoText(data.getTodayRevenue(), data.getAverageDailyRevenue()));
        lblStatRevenueInfo.setForeground(resolveRevenueInfoColor(data.getTodayRevenue(), data.getAverageDailyRevenue()));
    }

    private void applyLowStockStat(DashboardData data) {
        lblStatLowStockValue.setText(formatInteger(data.getLowStockItems()));
        lblStatLowStockInfo.setText(buildLowStockInfoText(data.getLowStockItems()));
        lblStatLowStockInfo.setForeground(data.getLowStockItems() > 0 ? COLOR_DANGER : COLOR_SUCCESS);
    }

    private void applyLoadError(Exception exception) {
        lblStatTodayVisitsValue.setText("-");
        lblStatTodayVisitsInfo.setText("Gagal memuat");
        lblStatTodayVisitsInfo.setForeground(COLOR_DANGER);

        lblStatPatientsValue.setText("-");
        lblStatPatientsInfo.setText("Gagal memuat");
        lblStatPatientsInfo.setForeground(COLOR_DANGER);

        lblStatRevenueValue.setText("-");
        lblStatRevenueInfo.setText("Gagal memuat");
        lblStatRevenueInfo.setForeground(COLOR_DANGER);

        lblStatLowStockValue.setText("-");
        lblStatLowStockInfo.setText("Gagal memuat");
        lblStatLowStockInfo.setForeground(COLOR_DANGER);

        applyRecentVisitPlaceholder("Gagal memuat data kunjungan");
        applyActiveQueuePlaceholder("Gagal memuat antrian");
        updateActiveQueuePaginationInfo();
        updateRecentVisitPaginationInfo();
        btnPrevActiveQueues.setEnabled(false);
        btnNextActiveQueues.setEnabled(false);

        String message = exception.getMessage();
        if (message != null && !message.isBlank()) {
            panelMain.setToolTipText(message);
        }
    }

    private void applyActiveQueues(List<DashboardQueueEntry> queues) {
        DefaultTableModel m = (DefaultTableModel) tblDataAntrianAktif.getModel();
        m.setRowCount(0);
        if (queues.isEmpty()) {
            showActiveQueuesEmptyState("Data not found");
            return;
        }

        for (DashboardQueueEntry queueEntry : queues) {
            m.addRow(new Object[]{
                defaultValue(queueEntry.getQueueNumber()),
                defaultValue(queueEntry.getPatientName()),
                defaultValue(queueEntry.getDoctorSummary()),
                defaultValue(queueEntry.getStatus())
            });
        }
        showActiveQueuesTable();
    }

    private void applyActiveQueuePage(DashboardActiveQueuePage pageData) {
        activeQueueCurrentPage = pageData.getCurrentPage();
        activeQueueTotalPages = pageData.getTotalPages();
        activeQueueTotalItems = pageData.getTotalItems();

        applyActiveQueues(pageData.getQueues());
        updateActiveQueuePaginationInfo();
        btnPrevActiveQueues.setEnabled(activeQueueCurrentPage > 1);
        btnNextActiveQueues.setEnabled(activeQueueCurrentPage < activeQueueTotalPages);
    }

    private void updateActiveQueuePaginationInfo() {
        lblActiveQueuePageInfo.setText(
                "Halaman "
                + formatInteger(activeQueueCurrentPage)
                + " dari "
                + formatInteger(activeQueueTotalPages)
                + " • "
                + formatInteger(activeQueueTotalItems)
                + " data"
        );
    }

    private void applyRecentVisits(List<DashboardRecentVisit> visits) {
        DefaultTableModel m = (DefaultTableModel) tblDataKunjungan.getModel();
        m.setRowCount(0);
        if (visits.isEmpty()) {
            showRecentVisitsEmptyState("Data not found");
            return;
        }

        for (DashboardRecentVisit visit : visits) {
            m.addRow(new Object[]{
                defaultValue(visit.getQueueNumber()),
                defaultValue(visit.getPatientName()),
                defaultValue(visit.getDoctorName()),
                defaultValue(visit.getStatus())
            });
        }
        showRecentVisitsTable();
    }

    private void applyRecentVisitPage(DashboardRecentVisitPage pageData) {
        recentVisitsCurrentPage = pageData.getCurrentPage();
        recentVisitsTotalPages = pageData.getTotalPages();
        recentVisitsTotalItems = pageData.getTotalItems();

        applyRecentVisits(pageData.getVisits());
        updateRecentVisitPaginationInfo();
        btnPrevRecentVisits.setEnabled(recentVisitsCurrentPage > 1);
        btnNextRecentVisits.setEnabled(recentVisitsCurrentPage < recentVisitsTotalPages);
        btnSearchRecentVisits.setEnabled(true);
        txtSearchRecentVisits.setEnabled(true);
    }

    private void updateRecentVisitPaginationInfo() {
        lblRecentVisitsPageInfo.setText(
                "Halaman "
                + formatInteger(recentVisitsCurrentPage)
                + " dari "
                + formatInteger(recentVisitsTotalPages)
                + " • "
                + formatInteger(recentVisitsTotalItems)
                + " data"
        );
    }

    private void applyRecentVisitPlaceholder(String message) {
        ((DefaultTableModel) tblDataKunjungan.getModel()).setRowCount(0);
        showRecentVisitsEmptyState(message);
    }

    private void applyActiveQueuePlaceholder(String message) {
        ((DefaultTableModel) tblDataAntrianAktif.getModel()).setRowCount(0);
        showActiveQueuesEmptyState(message);
    }

    private void showActiveQueuesTable() {
        if (jScrollPane2.getViewport().getView() != tblDataAntrianAktif) {
            jScrollPane2.setViewportView(tblDataAntrianAktif);
        }
        jScrollPane2.setColumnHeaderView(tblDataAntrianAktif.getTableHeader());
    }

    private void showActiveQueuesEmptyState(String message) {
        activeQueueEmptyStateLabel.setText(message == null || message.isBlank() ? "Data not found" : message);
        if (jScrollPane2.getViewport().getView() != activeQueueEmptyStateLabel) {
            jScrollPane2.setViewportView(activeQueueEmptyStateLabel);
        }
        jScrollPane2.setColumnHeaderView(tblDataAntrianAktif.getTableHeader());
    }

    private void showRecentVisitsTable() {
        if (jScrollPane1.getViewport().getView() != tblDataKunjungan) {
            jScrollPane1.setViewportView(tblDataKunjungan);
        }
        jScrollPane1.setColumnHeaderView(tblDataKunjungan.getTableHeader());
    }

    private void showRecentVisitsEmptyState(String message) {
        recentVisitsEmptyStateLabel.setText(message == null || message.isBlank() ? "Data not found" : message);
        if (jScrollPane1.getViewport().getView() != recentVisitsEmptyStateLabel) {
            jScrollPane1.setViewportView(recentVisitsEmptyStateLabel);
        }
        jScrollPane1.setColumnHeaderView(tblDataKunjungan.getTableHeader());
    }

    private class PaddedTableCellRenderer extends DefaultTableCellRenderer {

        private final int alignment;

        private PaddedTableCellRenderer(int alignment) {
            this.alignment = alignment;
        }

        @Override
        public Component getTableCellRendererComponent(
                JTable table,
                Object value,
                boolean isSelected,
                boolean hasFocus,
                int row,
                int column
        ) {
            super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            setHorizontalAlignment(alignment);
            setBorder(BorderFactory.createEmptyBorder(0, 12, 0, 12));
            setBackground(Color.WHITE);
            setForeground(new Color(32, 32, 32));
            return this;
        }
    }

    private final class StatusTableCellRenderer extends PaddedTableCellRenderer {

        private StatusTableCellRenderer() {
            super(SwingConstants.CENTER);
        }

        @Override
        public Component getTableCellRendererComponent(
                JTable table,
                Object value,
                boolean isSelected,
                boolean hasFocus,
                int row,
                int column
        ) {
            super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            String normalizedStatus = defaultValue(value == null ? null : value.toString());
            switch (normalizedStatus.toLowerCase(LOCALE_ID)) {
                case "selesai" -> setForeground(COLOR_SUCCESS);
                case "periksa" -> setForeground(COLOR_WARNING);
                case "blm bayar" -> setForeground(new Color(187, 73, 73));
                default -> setForeground(COLOR_NEUTRAL);
            }

            return this;
        }
    }

    private String buildVisitInfoText(int delta) {
        if (delta > 0) {
            return "+" + formatInteger(delta) + " dari kemarin";
        }

        if (delta < 0) {
            return formatInteger(delta) + " dari kemarin";
        }

        return "Sama seperti kemarin";
    }

    private String buildMonthlyPatientInfoText(int newPatientsThisMonth) {
        if (newPatientsThisMonth > 0) {
            return "+" + formatInteger(newPatientsThisMonth) + " bulan ini";
        }

        if (newPatientsThisMonth == 0) {
            return "Belum ada pasien baru";
        }

        return formatInteger(newPatientsThisMonth) + " bulan ini";
    }

    private String buildRevenueInfoText(BigDecimal todayRevenue, BigDecimal averageRevenue) {
        BigDecimal safeTodayRevenue = safeAmount(todayRevenue);
        BigDecimal safeAverageRevenue = safeAmount(averageRevenue);

        if (safeAverageRevenue.compareTo(BigDecimal.ZERO) <= 0) {
            return safeTodayRevenue.compareTo(BigDecimal.ZERO) > 0
                    ? "Pendapatan pertama tercatat"
                    : "Belum ada transaksi lunas";
        }

        BigDecimal percentDelta = safeTodayRevenue
                .subtract(safeAverageRevenue)
                .multiply(BigDecimal.valueOf(100))
                .divide(safeAverageRevenue, 0, RoundingMode.HALF_UP);

        int delta = percentDelta.intValue();
        if (delta > 0) {
            return "+" + delta + "% dari rata-rata";
        }

        if (delta < 0) {
            return delta + "% dari rata-rata";
        }

        return "Sesuai rata-rata";
    }

    private String buildLowStockInfoText(int lowStockItems) {
        if (lowStockItems > 0) {
            return "Perlu restock";
        }

        return "Stok aman";
    }

    private Color resolveDeltaColor(int delta) {
        if (delta > 0) {
            return COLOR_SUCCESS;
        }

        if (delta < 0) {
            return COLOR_DANGER;
        }

        return COLOR_MUTED;
    }

    private Color resolveRevenueInfoColor(BigDecimal todayRevenue, BigDecimal averageRevenue) {
        BigDecimal safeAverageRevenue = safeAmount(averageRevenue);
        if (safeAverageRevenue.compareTo(BigDecimal.ZERO) <= 0) {
            return COLOR_MUTED;
        }

        return safeAmount(todayRevenue).compareTo(safeAverageRevenue) >= 0 ? COLOR_SUCCESS : COLOR_DANGER;
    }

    private String formatInteger(int value) {
        NumberFormat format = NumberFormat.getIntegerInstance(LOCALE_ID);
        return format.format(value);
    }

    private String formatCompactCurrency(BigDecimal amount) {
        BigDecimal safeAmount = safeAmount(amount);
        BigDecimal oneBillion = BigDecimal.valueOf(1_000_000_000L);
        BigDecimal oneMillion = BigDecimal.valueOf(1_000_000L);
        BigDecimal oneThousand = BigDecimal.valueOf(1_000L);

        if (safeAmount.compareTo(oneBillion) >= 0) {
            return "Rp " + formatCompactNumber(safeAmount.divide(oneBillion, 1, RoundingMode.HALF_UP)) + "M";
        }

        if (safeAmount.compareTo(oneMillion) >= 0) {
            return "Rp " + formatCompactNumber(safeAmount.divide(oneMillion, 1, RoundingMode.HALF_UP)) + "jt";
        }

        if (safeAmount.compareTo(oneThousand) >= 0) {
            return "Rp " + formatCompactNumber(safeAmount.divide(oneThousand, 1, RoundingMode.HALF_UP)) + "rb";
        }

        return "Rp " + formatInteger(safeAmount.setScale(0, RoundingMode.HALF_UP).intValue());
    }

    private String formatCompactNumber(BigDecimal value) {
        DecimalFormatSymbols symbols = DecimalFormatSymbols.getInstance(LOCALE_ID);
        DecimalFormat format = new DecimalFormat("0.#", symbols);
        return format.format(value.stripTrailingZeros());
    }

    private BigDecimal safeAmount(BigDecimal value) {
        return value == null ? BigDecimal.ZERO : value;
    }

    private DashboardForm resolveDashboardForm() {
        Window window = SwingUtilities.getWindowAncestor(this);
        return window instanceof DashboardForm ? (DashboardForm) window : null;
    }

    private void navigateToPasienCreatePage() {
        DashboardForm dashboardForm = resolveDashboardForm();
        if (dashboardForm != null) {
            dashboardForm.showPasienCreatePage();
        }
    }

    private void navigateToKunjunganExaminationPage() {
        DashboardForm dashboardForm = resolveDashboardForm();
        if (dashboardForm != null) {
            dashboardForm.showKunjunganExaminationPage();
        }
    }

    private void navigateToPembayaranListPage() {
        DashboardForm dashboardForm = resolveDashboardForm();
        if (dashboardForm != null) {
            dashboardForm.showPembayaranListPage();
        }
    }

    private void navigateToDailyReportPage() {
        DashboardForm dashboardForm = resolveDashboardForm();
        if (dashboardForm != null) {
            dashboardForm.showDailyReportPage();
        }
    }

    private String defaultValue(String value) {
        if (value == null || value.isBlank()) {
            return "-";
        }

        return value.trim();
    }

    private String capitalizeFirstLetter(String text) {
        if (text == null || text.isBlank()) {
            return "";
        }

        return text.substring(0, 1).toUpperCase(LOCALE_ID) + text.substring(1);
    }
}
