package com.release.klinikgaharumedika.view;

import com.release.klinikgaharumedika.model.Dokter;
import com.release.klinikgaharumedika.model.Kunjungan;
import com.release.klinikgaharumedika.model.Obat;
import com.release.klinikgaharumedika.model.Pasien;
import com.release.klinikgaharumedika.model.Pembayaran;
import com.release.klinikgaharumedika.model.Perawat;
import com.release.klinikgaharumedika.model.User;
import com.release.klinikgaharumedika.state.SessionManager;
import com.release.klinikgaharumedika.view.panel.DashboardPanel;
import com.release.klinikgaharumedika.view.panel.DokterFormPanel;
import com.release.klinikgaharumedika.view.panel.DokterPanel;
import com.release.klinikgaharumedika.view.panel.KunjunganFormPanel;
import com.release.klinikgaharumedika.view.panel.KunjunganPanel;
import com.release.klinikgaharumedika.view.panel.LaporanPanel;
import com.release.klinikgaharumedika.view.panel.ObatFormPanel;
import com.release.klinikgaharumedika.view.panel.ObatPanel;
import com.release.klinikgaharumedika.view.panel.PasienFormPanel;
import com.release.klinikgaharumedika.view.panel.PasienPanel;
import com.release.klinikgaharumedika.view.panel.PembayaranFormPanel;
import com.release.klinikgaharumedika.view.panel.PembayaranPanel;
import com.release.klinikgaharumedika.view.panel.PerawatFormPanel;
import com.release.klinikgaharumedika.view.panel.PerawatPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;

public class DashboardForm extends javax.swing.JFrame {

    private final User user;

    public DashboardForm(User user) {
        this.user = user;
        initComponents();
        setLocationRelativeTo(null);
        panelContentHost.setLayout(new BorderLayout());
        applyUserInfo();
        showDashboardPage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRoot = new javax.swing.JPanel();
        panelSidebar = new javax.swing.JPanel();
        lblBrandIcon = new javax.swing.JLabel();
        lblBrandTitle = new javax.swing.JLabel();
        lblBrandSubtitle = new javax.swing.JLabel();
        lblMenuUtama = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        lblMenuMaster = new javax.swing.JLabel();
        btnPasien = new javax.swing.JButton();
        btnDokter = new javax.swing.JButton();
        btnObat = new javax.swing.JButton();
        btnPerawat = new javax.swing.JButton();
        lblMenuTransaksi = new javax.swing.JLabel();
        btnKunjungan = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        lblMenuLaporan = new javax.swing.JLabel();
        btnLaporan = new javax.swing.JButton();
        panelUserCard = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        lblUserRole = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        panelMain = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lblPageTitle = new javax.swing.JLabel();
        lblPageSubtitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelContentHost = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard - Klinik Gaharu Medika");
        setMinimumSize(new java.awt.Dimension(1200, 760));

        panelRoot.setBackground(new java.awt.Color(243, 240, 233));

        panelSidebar.setBackground(new java.awt.Color(255, 255, 255));
        panelSidebar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(225, 220, 210)));
        panelSidebar.setPreferredSize(new java.awt.Dimension(240, 720));

        lblBrandIcon.setBackground(new java.awt.Color(28, 112, 77));
        lblBrandIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBrandIcon.setForeground(new java.awt.Color(255, 255, 255));
        lblBrandIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrandIcon.setText("G");
        lblBrandIcon.setOpaque(true);

        lblBrandTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBrandTitle.setText("Gaharu Medika");

        lblBrandSubtitle.setForeground(new java.awt.Color(120, 120, 120));
        lblBrandSubtitle.setText("Manajemen Klinik");

        lblMenuUtama.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblMenuUtama.setForeground(new java.awt.Color(150, 150, 150));
        lblMenuUtama.setText("UTAMA");

        btnDashboard.setText("Dashboard");
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        lblMenuMaster.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblMenuMaster.setForeground(new java.awt.Color(150, 150, 150));
        lblMenuMaster.setText("MASTER DATA");

        btnPasien.setText("Pasien");
        btnPasien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasienActionPerformed(evt);
            }
        });

        btnDokter.setText("Dokter");
        btnDokter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDokterActionPerformed(evt);
            }
        });

        btnObat.setText("Obat");
        btnObat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObatActionPerformed(evt);
            }
        });

        btnPerawat.setText("Perawat");
        btnPerawat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerawatActionPerformed(evt);
            }
        });

        lblMenuTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblMenuTransaksi.setForeground(new java.awt.Color(150, 150, 150));
        lblMenuTransaksi.setText("TRANSAKSI");

        btnKunjungan.setText("Kunjungan");
        btnKunjungan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKunjungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKunjunganActionPerformed(evt);
            }
        });

        btnPembayaran.setText("Pembayaran");
        btnPembayaran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });

        lblMenuLaporan.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblMenuLaporan.setForeground(new java.awt.Color(150, 150, 150));
        lblMenuLaporan.setText("LAPORAN");

        btnLaporan.setText("Laporan");
        btnLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        panelUserCard.setBackground(new java.awt.Color(250, 250, 248));
        panelUserCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 218, 208)));

        lblUserName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserName.setText("Nama User");

        lblUserRole.setForeground(new java.awt.Color(120, 120, 120));
        lblUserRole.setText("Role");

        btnLogout.setText("Keluar");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUserCardLayout = new javax.swing.GroupLayout(panelUserCard);
        panelUserCard.setLayout(panelUserCardLayout);
        panelUserCardLayout.setHorizontalGroup(
            panelUserCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserCardLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelUserCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(lblUserName)
                    .addComponent(lblUserRole))
                .addGap(16, 16, 16))
        );
        panelUserCardLayout.setVerticalGroup(
            panelUserCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserCardLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserRole)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMenuUtama)
                    .addComponent(lblMenuMaster)
                    .addComponent(lblMenuTransaksi)
                    .addComponent(lblMenuLaporan)
                    .addComponent(panelUserCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addComponent(lblBrandIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBrandTitle)
                            .addComponent(lblBrandSubtitle)))
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPerawat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKunjungan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBrandIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addComponent(lblBrandTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblBrandSubtitle)))
                .addGap(24, 24, 24)
                .addComponent(lblMenuUtama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDashboard)
                .addGap(18, 18, 18)
                .addComponent(lblMenuMaster)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDokter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnObat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPerawat)
                .addGap(18, 18, 18)
                .addComponent(lblMenuTransaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKunjungan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPembayaran)
                .addGap(18, 18, 18)
                .addComponent(lblMenuLaporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLaporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(panelUserCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        panelMain.setBackground(new java.awt.Color(243, 240, 233));

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 218, 208)));

        lblPageTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPageTitle.setText("Dashboard");

        lblPageSubtitle.setForeground(new java.awt.Color(120, 120, 120));
        lblPageSubtitle.setText("Ringkasan utama aktivitas klinik.");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPageTitle)
                            .addComponent(lblPageSubtitle))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblPageTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPageSubtitle)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelContentHost.setBackground(new java.awt.Color(243, 240, 233));

        javax.swing.GroupLayout panelContentHostLayout = new javax.swing.GroupLayout(panelContentHost);
        panelContentHost.setLayout(panelContentHostLayout);
        panelContentHostLayout.setHorizontalGroup(
            panelContentHostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
        );
        panelContentHostLayout.setVerticalGroup(
            panelContentHostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContentHost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(panelContentHost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout panelRootLayout = new javax.swing.GroupLayout(panelRoot);
        panelRoot.setLayout(panelRootLayout);
        panelRootLayout.setHorizontalGroup(
            panelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRootLayout.createSequentialGroup()
                .addComponent(panelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRootLayout.setVerticalGroup(
            panelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        showDashboardPage();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasienActionPerformed
        showPasienPage();
    }//GEN-LAST:event_btnPasienActionPerformed

    private void btnDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDokterActionPerformed
        showDokterPage();
    }//GEN-LAST:event_btnDokterActionPerformed

    private void btnObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObatActionPerformed
        showObatPage();
    }//GEN-LAST:event_btnObatActionPerformed

    private void btnPerawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerawatActionPerformed
        showPerawatPage();
    }//GEN-LAST:event_btnPerawatActionPerformed

    private void btnKunjunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKunjunganActionPerformed
        showKunjunganPage();
    }//GEN-LAST:event_btnKunjunganActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        showPembayaranPage();
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        showLaporanPage();
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        SessionManager.getInstance().clear();
        new LoginForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void applyUserInfo() {
        lblUserName.setText(user.getDisplayName());
        lblUserRole.setText(capitalizeRole(user.getRole()));
    }

    public void showDashboardPage() {
        openPage(new DashboardPanel(), "Dashboard", "Ringkasan utama aktivitas klinik.");
        setActiveMenu(btnDashboard);
    }

    public void showPasienPage() {
        openPage(new PasienPanel(), "Pasien", "Kelola data pasien melalui panel yang bisa kamu edit di designer.");
        setActiveMenu(btnPasien);
    }

    public void showPasienCreatePage() {
        openPage(new PasienFormPanel(), "Tambah Pasien Baru", "Form registrasi pasien baru dari dashboard.");
        setActiveMenu(btnPasien);
    }

    public void showPasienEditPage(Pasien pasien) {
        openPage(new PasienFormPanel(pasien), "Edit Pasien", "Perbarui master data pasien.");
        setActiveMenu(btnPasien);
    }

    public void showDokterPage() {
        openPage(new DokterPanel(), "Dokter", "Kelola data dokter melalui panel yang bisa kamu edit di designer.");
        setActiveMenu(btnDokter);
    }

    public void showDokterCreatePage() {
        openPage(new DokterFormPanel(), "Tambah Dokter", "Master data dokter dan jadwal praktik.");
        setActiveMenu(btnDokter);
    }

    public void showDokterEditPage(Dokter dokter) {
        openPage(new DokterFormPanel(dokter), "Edit Dokter", "Perbarui master data dokter dan jadwal praktik.");
        setActiveMenu(btnDokter);
    }

    public void showObatPage() {
        openPage(new ObatPanel(), "Obat", "Kelola data obat melalui panel yang bisa kamu edit di designer.");
        setActiveMenu(btnObat);
    }

    public void showObatCreatePage() {
        openPage(new ObatFormPanel(), "Tambah Obat", "Master data obat, stok, dan harga.");
        setActiveMenu(btnObat);
    }

    public void showObatEditPage(Obat obat) {
        openPage(new ObatFormPanel(obat), "Edit Obat", "Perbarui master data obat.");
        setActiveMenu(btnObat);
    }

    public void showPerawatPage() {
        openPage(new PerawatPanel(), "Perawat", "Kelola data perawat melalui panel yang bisa kamu edit di designer.");
        setActiveMenu(btnPerawat);
    }

    public void showPerawatCreatePage() {
        openPage(new PerawatFormPanel(), "Tambah Perawat", "Master data perawat.");
        setActiveMenu(btnPerawat);
    }

    public void showPerawatEditPage(Perawat perawat) {
        openPage(new PerawatFormPanel(perawat), "Edit Perawat", "Perbarui master data perawat.");
        setActiveMenu(btnPerawat);
    }

    public void showKunjunganPage() {
        openPage(new KunjunganPanel(), "Kunjungan", "Kelola data kunjungan melalui panel yang bisa kamu edit di designer.");
        setActiveMenu(btnKunjungan);
    }

    public void showKunjunganCreatePage() {
        openPage(new KunjunganFormPanel(), "Pendaftaran Kunjungan", "Form pendaftaran dan pemeriksaan pasien.");
        setActiveMenu(btnKunjungan);
    }

    public void showKunjunganEditPage(Kunjungan kunjungan) {
        openPage(new KunjunganFormPanel(kunjungan), "Edit Kunjungan", "Perbarui data pendaftaran, pemeriksaan, dan resep.");
        setActiveMenu(btnKunjungan);
    }

    public void showKunjunganExaminationPage() {
        showKunjunganCreatePage();
    }

    public void showPembayaranPage() {
        openPage(new PembayaranPanel(), "Pembayaran", "Kelola data pembayaran melalui panel yang bisa kamu edit di designer.");
        setActiveMenu(btnPembayaran);
    }

    public void showPembayaranListPage() {
        openPage(new PembayaranPanel(true), "Daftar Pembayaran", "Daftar pembayaran pasien yang siap diproses.");
        setActiveMenu(btnPembayaran);
    }

    public void showPembayaranFormPage(Pembayaran pembayaran) {
        openPage(new PembayaranFormPanel(pembayaran), "Form Pembayaran", "Proses pelunasan tagihan kunjungan pasien.");
        setActiveMenu(btnPembayaran);
    }

    public void showLaporanPage() {
        openPage(new LaporanPanel(), "Laporan", "Kelola data laporan melalui panel yang bisa kamu edit di designer.");
        setActiveMenu(btnLaporan);
    }

    public void showDailyReportPage() {
        openPage(new LaporanPanel(true), "Laporan Hari Ini", "Ringkasan laporan operasional harian.");
        setActiveMenu(btnLaporan);
    }

    private void openPage(JPanel page, String title, String subtitle) {
        boolean isDashboardPage = page instanceof DashboardPanel;
        lblPageTitle.setText(title);
        lblPageSubtitle.setText(subtitle);
        panelHeader.setVisible(isDashboardPage);
        panelContentHost.removeAll();
        panelContentHost.add(page, BorderLayout.CENTER);
        panelContentHost.revalidate();
        panelContentHost.repaint();
    }

    private void setActiveMenu(JButton activeButton) {
        JButton[] buttons = {
            btnDashboard, btnPasien, btnDokter, btnObat,
            btnPerawat, btnKunjungan, btnPembayaran, btnLaporan
        };

        for (JButton button : buttons) {
            boolean active = button == activeButton;
            button.setBackground(active ? new Color(231, 243, 237) : Color.WHITE);
            button.setForeground(active ? new Color(28, 112, 77) : new Color(70, 70, 70));
            button.setOpaque(true);
            button.setBorderPainted(false);
            button.setFocusPainted(false);
        }
    }

    private String capitalizeRole(String role) {
        if (role == null || role.isBlank()) {
            return "-";
        }

        return role.substring(0, 1).toUpperCase() + role.substring(1).toLowerCase();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDokter;
    private javax.swing.JButton btnKunjungan;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnObat;
    private javax.swing.JButton btnPasien;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnPerawat;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBrandIcon;
    private javax.swing.JLabel lblBrandSubtitle;
    private javax.swing.JLabel lblBrandTitle;
    private javax.swing.JLabel lblMenuLaporan;
    private javax.swing.JLabel lblMenuMaster;
    private javax.swing.JLabel lblMenuTransaksi;
    private javax.swing.JLabel lblMenuUtama;
    private javax.swing.JLabel lblPageSubtitle;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserRole;
    private javax.swing.JPanel panelContentHost;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelRoot;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JPanel panelUserCard;
    // End of variables declaration//GEN-END:variables
}
